console.log('Доступные команды')
console.log('npm run batch_create - создание n количества braavos кошельков')
console.log('npm run starkgate_bridge - бридж из eth в Starknet, используя оффициальный мост')
console.log('npm run starkgate_fee - просмотр комисии моста')
console.log('npm run main - главный скрипт')
console.log('npm run okx_refuel - трансфер ETH с okx на аккаунты Starknet')