export interface Iconfig {
    stableSwap: boolean,
    jediSwap: boolean,
    jediSwap_liq: boolean,
    l0kswap: boolean,
    mySwap: boolean,
    dmail: boolean,
    stable_amount_to_swap: number[], 
    slippage: number,
    minGasPrice: number,
    Dmail_mails_count: number[],
    batch_create: boolean,
    batch_create_number: number,
    starkgate: boolean,
    starkgate_amount: string,
    starkgate_show_fee: boolean,
    upgrade: boolean,
    stableSwap_full_balance: boolean,
    jediSwap_liq_amount: number[],
    sleep: number[],
    protocols: number[],
}