import { network } from "../orbiter/bridgeData"

export interface Iconfig {
    stableSwap: boolean,
    jediSwap: boolean,
    jediSwap_liq: boolean,
    l0kswap: boolean,
    mySwap: boolean,
    dmail: boolean,
    stable_amount_to_swap: number[], 
    slippage: number,
    minGasPrice: number,
    Dmail_mails_count: number[],
    starkgate_amount: string,
    upgrade: boolean,
    stableSwap_full_balance: boolean,
    jediSwap_liq_amount: number[],
    sleep_protocols: number[],
    sleep_account: number[],
    protocols: number[],
    refuel_threshold: string,
    orbiter_to_evm: boolean,
    orbiter_amount: string,
    orbiter_to_network: network,
    orbiter_to_evm_address?: string,
    orbiter_bridge_full_ETH: boolean,
    okx_apiKey: string,
    okx_passPhrase: string,
    okx_secretKey: string,
    okx_withdraw_amount: number[],
    okx_sleep_min: number,
    okx_sleep_max: number,
    okx_deposit_address?: string,
    okx_deposit?: boolean,
    rpc_url?: string,
    mint_starkId: boolean,
    jediswap_liq_withdraw: boolean,
    starkgate_bridge_full_ETH: boolean,
}